apiVersion: v1
kind: Pod
metadata:
  name: jhooq-pod-with-pvc
  labels:
    name: jhooq-pod-with-pvc
spec:
  containers:
    - name: jhooq-pod-with-pvc
      image: nginx
      ports:
        - containerPort: 80
          name: www
      volumeMounts:
        - name: www-persistent-storage
          mountPath: /opt/k8s-volume
  volumes:
    - name: www-persistent-storage
      persistentVolumeClaim:
        claimName: jhooq-pvc

