apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
  - name: mycontainer
    image: nginx
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: example-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: example-secret
          key: password

