apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - kube-worker-1
  containers:
  - name: nginx
    image: nginx:latest

