apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer   #(you need have external loadbalancer or metal LB for this type of service)

